# Generated by Django 5.1.1 on 2024-09-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SOME STRING', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Enter a description', null=True, verbose_name='Description')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('project_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Lien du projet')),
                ('techs', models.JSONField(default=dict)),
            ],
        ),
    ]
